### ISSUE TITLE
Session Warnings

### ISSUE THREAD

**Issue by gjerdery** [jaredcowing/wmsNewBooks#3]
All pages loaded in the browser have two session related warnings at the bottom. From looking through the ci_sessions directory, the files indicated ARE being created.

A PHP Error was encountered
Severity: Warning

Message: touch(): Unable to create file ci_sessions/ci_sessionpn3gtlusf57knpga9oo0avgvuq22mb29 because No such file or directory

Filename: drivers/Session_files_driver.php

Line Number: 248

Backtrace:

________________________________________

A PHP Error was encountered
Severity: Warning

Message: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ci_sessions)

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by jaredcowing** [comment]
Hmm, this looks like a CodeIgniter error. I might need to do a little homework to see what might be the culprit (will let you know if I find anything).

**Comment by gjerdery** [comment]
I figured this one out - since I'm using SQLite3, I needed to set an absolute path to the sessions directory in config.php, like this:
$config['sess_save_path'] = BASEPATH . 'ci_sessions';

**Comment by jaredcowing** [comment]
Glad that it could be resolved, I'll take note of the extra requirement for SCLite3.
